#post new url 
POST http://local.sivir.pw:8080/add HTTP/1.1
Content-Type: application/json

{
    "url": "https://microsoft.com"
}

### fetch exist url 
GET http://local.sivir.pw:8080/q/7nnW9KH HTTP/1.1

#post new url 
POST https://asia-east1-sivir-pw.cloudfunctions.net/redirect /add HTTP/1.1
Content-Type: application/json

{
    "url": "https://microsoft.com"
}

### fetch exist url 
GET https://asia-east1-sivir-pw.cloudfunctions.net/redirect/q/7nnW9KH HTTP/1.1
